name: Publish package on NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Production Build and Publish
        env:
          VITE_API_BASE_URL: "https://api.genez.io"
          VITE_VERSION: "0.3.0"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install --legacy-peer-deps
          npm run build
          npm publish --access=public
      - name: Generate Dev Version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          DEV_VERSION="${CURRENT_VERSION}-dev"
          echo "DEV_VERSION=${DEV_VERSION}" >> $GITHUB_OUTPUT
          npm version $DEV_VERSION --no-git-tag-version
      - name: Development Build and Publish
        env:
          VITE_API_BASE_URL: "https://dev.api.genez.io"
          VITE_VERSION: "0.3.0"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install --legacy-peer-deps
          npm run build
          npm publish --tag dev --access=public
